const styles=[
  {id:'01-pocket-coast',number:'01',title:'Pocket Coast',category:'8-bit / colour handheld',chip:'CHUNKY PIXELS',color:'#336c3f',heading:'Small pixels. Big personality.',description:'The simplest silhouettes in the group. A compact, cheeky world that puts immediate readability first.',shapes:'Broad bodies, dot eyes, hard dark outlines and a handful of flat colour clusters.',view:'Top-down paths, repeated tiles and graphic trees. The screen feels like one complete little room.',fit:'A direction worth testing at the existing native dimensions. The generated board still needs to be redrawn on an exact pixel grid.',summary:'Bold outlines, tiny faces and a world made of simple, confident shapes.',character:'Compact, broad, playful',equipment:'Pictographic shapes',world:'Orthographic tile room'},
  {id:'02-sunlit-adventure',number:'02',title:'Sunlit Adventure',category:'16-bit / GBA adventure',chip:'SOFT PIXELS',color:'#cb852b',heading:'A warmer kind of adventure.',description:'Rounded forms and warm materials give the working day a storybook feeling while keeping a pixel-art vocabulary.',shapes:'Coloured outlines, rounded clusters, soft cap brims and carefully placed highlights.',view:'Lush top-down scenery, honey stone and bright water. Small wall faces add gentle depth.',fit:'My strongest starting point for a richer 2D direction. Simplify the illustration into the existing 24-pixel and 16-pixel budgets before integrating.',summary:'Softer outlines, rounded foliage and the warmth of a handheld adventure.',character:'Round, friendly, tactile',equipment:'Bright little treasures',world:'Layered 2D courtyard'},
  {id:'03-coastal-storybook',number:'03',title:'Coastal Storybook',category:'Illustrated / fantasy RPG',chip:'DRAWN & INKED',color:'#a56343',heading:'Every object has a story.',description:'A more theatrical keeper and sculptural tools. The ordinary cap, net and clogs become equipment with real personality.',shapes:'Tapered ink contours, long limbs, oversized accessories and asymmetric silhouettes.',view:'A softly crooked courtyard with warm timber and limestone, seen at an oblique angle.',fit:'Best for richer paper-doll portraits and equipment illustrations. The smooth linework needs more pixels than the current sprites provide.',summary:'Expressive ink, unusual proportions and equipment with a little attitude.',character:'Lanky, expressive, quirky',equipment:'Sculptural fantasy loot',world:'Drawn oblique courtyard'},
  {id:'04-tideglass-tactics',number:'04',title:'Tideglass Tactics',category:'Graphic / isometric tactics',chip:'FACETED & CLEAN',color:'#168a91',heading:'A little island of possibility.',description:'A modern, airy tactical direction. Strong facets and large colour blocks give the keeper and pool monsters clear silhouettes.',shapes:'Angular limbs, cap wedges, broad mechanical forms and crisp cel-shaded planes.',view:'A compact raised island with the pool and depot on one playable surface. Short cliffs reveal its depth.',fit:'A direction for a future 2.5D experiment with higher-resolution sprites, depth sorting and bespoke diamond tiles.',summary:'Angular characters, clean equipment and a pool courtyard on an island.',character:'Angular, confident, graphic',equipment:'Clean, gem-like icons',world:'Raised isometric island'},
];
const baseline={id:'00-field-kit-baseline',number:'00',title:'Original field kit',category:'The first study / comparison baseline',color:'#2f4fdf',heading:'Where the exploration began.',description:'The first Lacanau concept: detailed coastal scenery, a practical blue keeper and the five residence sets.',shapes:'Dense pixel-style detailing, expressive rounded companions and familiar workwear.',view:'A warm orthographic pool courtyard with pines, sand and blue timber.',fit:'This is the original generated concept. The v1 lab contains its separately authored native-pixel trials.',prompt:'prompts/00-field-kit-baseline.txt'};
const all=[...styles,baseline],$=s=>document.querySelector(s);let selected=styles[0];
const file=s=>`styles/${s.id}.png`;
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;}
function showOverview(){ $('#overview').hidden=false;$('#focus-view').hidden=true;$('#compare').setAttribute('aria-pressed','true');document.querySelectorAll('[data-style]').forEach(b=>b.setAttribute('aria-pressed','false'));history.replaceState(null,'',location.pathname+location.search);}
function focus(s,scroll=false){
  selected=s;$('#overview').hidden=true;$('#focus-view').hidden=false;$('#compare').setAttribute('aria-pressed','false');
  document.querySelectorAll('[data-style]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.style===s.id)));
  $('#focus-category').textContent=s.category.toUpperCase();$('#focus-title').textContent=s.title;
  $('#focus-image').src=file(s);$('#focus-image').alt=`${s.title}: the Lacanau pool courtyard, keeper, creatures, five outfits and equipment.`;
  $('#download').href=file(s);$('#detail-number').textContent=s.number;$('#detail-number').style.color=s.color;
  $('#detail-heading').textContent=s.heading;$('#detail-description').textContent=s.description;$('#detail-shapes').textContent=s.shapes;$('#detail-view').textContent=s.view;$('#detail-fit').textContent=s.fit;
  $('#prompt-link').href=s.prompt||`prompts/${s.id}.txt`;
  history.replaceState(null,'',`#${s.id}`);
  if(scroll)$('#focus-view').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
}
function expand(s){
  $('#lightbox-title').textContent=s.title;$('#lightbox-image').src=file(s);$('#lightbox-image').alt=`Full ${s.title} art-direction board`;$('#lightbox-download').href=file(s);$('#lightbox').showModal();
}
for(const s of all){
  const b=node('button');b.type='button';b.dataset.style=s.id;b.setAttribute('aria-pressed','false');b.append(node('b','',s.number),document.createTextNode(s.number==='00'?'Original':s.title));b.addEventListener('click',()=>focus(s));$('#style-nav').append(b);
}
for(const s of styles){
  const card=node('article','study-card');card.style.setProperty('--color',s.color);
  const top=node('div','card-top'),title=node('div');title.append(node('span','card-number',s.number),node('h2','',s.title));top.append(title,node('span','chip',s.chip));
  const button=node('button','board-button');button.type='button';button.setAttribute('aria-label',`Enlarge ${s.title}`);
  const img=node('img');img.src=file(s);img.width=1536;img.height=1024;img.alt=`${s.title} comparison board with pool courtyard, keeper, monsters and equipment.`;button.append(img);button.addEventListener('click',()=>expand(s));
  const bottom=node('div','card-bottom'),links=node('div','card-links'),details=node('button','', 'Explore direction ↗'),download=node('a','', 'PNG ↓');details.type='button';details.addEventListener('click',()=>focus(s,true));download.href=file(s);download.download='';download.setAttribute('aria-label',`Download ${s.title} PNG`);links.append(details,download);bottom.append(node('p','',s.summary),links);card.append(top,button,bottom);$('#cards').append(card);
  const row=node('tr'),name=node('td');name.style.setProperty('--color',s.color);name.append(node('span'),document.createTextNode(s.title));row.append(name,node('td','',s.character),node('td','',s.equipment),node('td','',s.world));$('#comparison-rows').append(row);
}
$('#compare').addEventListener('click',showOverview);$('#expand').addEventListener('click',()=>expand(selected));$('#focus-image-button').addEventListener('click',()=>expand(selected));$('#close-lightbox').addEventListener('click',()=>$('#lightbox').close());
$('#lightbox').addEventListener('click',event=>{const r=event.currentTarget.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)event.currentTarget.close();});
const initial=all.find(s=>s.id===location.hash.slice(1));if(initial)focus(initial);else showOverview();
